# Generated by Django 4.2.6 on 2023-10-10 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_birthdate_user_is_emplloyee_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_emplloyee',
            new_name='is_employee',
        ),
    ]
