# Generated by Django 4.2.6 on 2023-10-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_is_emplloyee_user_is_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=127, unique=True),
        ),
    ]
