# Generated by Django 4.2.6 on 2023-10-13 16:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_alter_movie_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='orders',
            field=models.ManyToManyField(related_name='movies_orders', through='movies_orders.MovieOrder', to=settings.AUTH_USER_MODEL),
        ),
    ]
